### ISSUE TITLE
Upgrade to Tosca 15.0

### ISSUE THREAD

**Issue by albertpuente** [Boehringer-Ingelheim/toscaci#44]
Previously missing functionality such as timestamp (testsuite level) information is now available in the junit files starting with 15.0.

**Comment by metmajer** [comment]
Do you know about Tosca v15's ability to have time stamps for each test case? This is what we will need. FYI @clemensutschig

**Comment by albertpuente** [comment]
As far as I know the have only added the standard timestamp field at the testsuite level.
